### ISSUE TITLE
Pre-launch checklist

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/data-registry#95]
OCP:

* [x] YL: Check for missing publications. Create an issue for Jan to start the processing of those datasets. #92 
* UI text
  * [x] JM/SZ: Check UI text (skipped – defer to comms team)
  * [x] JM: Ask Sophie A and Georg for copy-writing
  * [x] SA/GN: Do copy-editing
  * [x] YL: Coordinate translation of UI text to Spanish and Russian #97
* Dataset descriptions
  * [x] JM: Read English dataset descriptions for content (skipped - defer to comms team)
  * [x] JM: Ask Sophie A and Georg for copy-writing
  * [x] SA/GN: Do copy-editing
  * [x] YL: Assign the preparation of quality summaries to helpdesk analysts
  * [x] YL: Assign Spanish and Russian translations after copy-writing is done
  * [x] JM/YL: Fill in final text for all datasets and check metadata
  * [x] JM/YL: Put “We have not yet prepared a data quality summary for this dataset.” if missing
  * [x] JM: Decide what to do about licensing, since we found no lawyers to help ([sheet](https://docs.google.com/spreadsheets/d/1OmL53-_PLPgJZFqxx0iwHRbRvB597bKPo5Kl6vuA_7U/edit#gid=0))
* Application testing
  * [ ] Test the registry-spoonbill integration, especially with files that would exceed Excel's limits
  * [x] SZ to run through all screens, to check we didn't miss something
* Deployment
  * [x] Delete /var/www/.htpasswd (basic authentication)
  * [x] Remove symlinks /data/kingfisher-collect and /data/logs once new env files are deployed

Quintagroup:

* [x] Deploy Spoonbill to the production server, so that it is ready for integration by Datlab

Datlab/OCP:

* [ ] Activate scheduled runs of all active sources (@yolile can identify those that have stopped publishing)
* [x] @hrubyjan said some collections might need to be re-processed, because they were processed with older code
  * Before re-processing, check for a completed job first, since it just might not be active (e.g. Colombia needs the date ranges, etc. to be filled in, due to a migration error).
* [x] Implement feedback email
* [x] Check for any other blockers to launch

Dogsbody:

* [x] Set up data.open-contracting.org
* [ ] Review [open deploy issues tagged 'registry'](https://github.com/open-contracting/deploy/issues?q=is%3Aissue+is%3Aopen+label%3Aregistry)
* Discuss whether to switch from gunicorn to uWSGI (used in all other apps)
  * JM: I think gunicorn makes more sense inside Docker, since uWSGI requires a lot of configuration.
* VACUUM FULL or similar to reduce size of DB https://github.com/open-contracting/deploy/issues/290
* Backup the data registry database and the export dumps: https://github.com/open-contracting/deploy/issues/289
* Suggestion: for data registry, hot backup in read-only mode, low CPU, etc. requirements, just need large enough drives – need to ask Quinta about Spoonbill: https://github.com/open-contracting/deploy/issues/289

Post-launch:

* [ ] JM: Add data.open-contracting.org and flatten.open-contracting.org to Google Webmaster Central and Google Search Console

@hrubyjan Please add anything that is missing.

**Comment by jpmckinney** [comment]
> Test the registry-spoonbill integration, especially with files that would exceed Excel's limits

https://github.com/open-contracting/data-registry/issues/180

> Activate scheduled runs of all active sources

Management command has a cron job. Related: #181

> Add data.open-contracting.org and flatten.open-contracting.org to Google Webmaster Central and Google Search Console

https://github.com/open-contracting/deploy/issues/336
